openapi: 3.0.0
info:
  title: Kuburan Tentara
  version: 1.0.0
servers:
  - url: https://130.162.195.228
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: AUTH
  - name: Data Mayat
  - name: Plot Pemakaman
  - name: Kuburan
  - name: Pengelola Pemakaman
  - name: Kunjungan
paths:
  /mhs714220016/regis:
    post:
      tags:
        - AUTH
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: roger
                email: rogeroyen12@gmail.com
                password: oyen
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220016/login:
    post:
      tags:
        - AUTH
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: roger
                email: rogeroyen12@gmail.com
                password: oyen
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220016/datamayat:
    get:
      tags:
        - Data Mayat
      summary: GET
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Data Mayat
      summary: POST
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama_lengkap: Snusnu Rilety
                pangkat: Jendral
                tanggal_lahir: '1998-11-01'
                tanggal_wafat: '2024-02-21'
                nomor_identitas: '80009233'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220016/datamayat/{id}:
    delete:
      tags:
        - Data Mayat
      summary: DELETE
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - Data Mayat
      summary: PUT
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama_lengkap: Snusnu Riley
                pangkat: Jendral
                tanggal_lahir: '1998-11-01'
                tanggal_wafat: '2024-02-21'
                nomor_identitas: '80009233'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220016/plotpemakaman:
    get:
      tags:
        - Plot Pemakaman
      summary: GET
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Plot Pemakaman
      summary: POST
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nomor_plot: A2
                status_plot: Tersedia
                keterangan: Plot untuk tentara A2
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220016/plotpemakaman/{id}:
    put:
      tags:
        - Plot Pemakaman
      summary: PUT
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nomor_plot: A2
                status_plot: Terisi
                keterangan: Plot untuk tentara A2
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Plot Pemakaman
      summary: DELETE
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220016/kuburan:
    get:
      tags:
        - Kuburan
      summary: GET
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Kuburan
      summary: POST
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                plot_id: 2
                tentara_id: 3
                nomor_kuburan: '02'
                tanggal_dikubur: '2024-02-21'
                status_kuburan: terawat
                keterangan: kuburannya Snusnu
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220016/kuburan/{id}:
    put:
      tags:
        - Kuburan
      summary: PUT
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                plot_id: 2
                tentara_id: 3
                nomor_kuburan: '04'
                tanggal_dikubur: '2024-02-21'
                status_kuburan: terawat
                keterangan: kuburannya Snusnu
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Kuburan
      summary: DELETE
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220016/pengelolapemakaman:
    get:
      tags:
        - Pengelola Pemakaman
      summary: GET
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Pengelola Pemakaman
      summary: POST
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama_lengkap: Hudza Grahitama
                jabatan: Leutenant
                nomor_telepon: '0858675544'
                email: grahhudza@gmail.com
                alamat: Jl. Sukma 2 Block 6 No.23
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220016/pengelolapemakaman/{id}:
    put:
      tags:
        - Pengelola Pemakaman
      summary: PUT
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama_lengkap: Hudza Grahitama
                jabatan: Leutenant
                nomor_telepon: '0858675544'
                email: grahhudza@gmail.com
                alamat: Jl. Sukma 2 Block 6 No.123
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220016/pengelolapemakaman/{id}:
    delete:
      tags:
        - Pengelola Pemakaman
      summary: DELETE
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220016/kunjungan:
    get:
      tags:
        - Kunjungan
      summary: GET
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Kunjungan
      summary: POST
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                kuburan_id: 3
                tanggal_kunjungan: '2024-05-20'
                nama_pengunjung: Zamy Skibidi
                hubungan: friends
                keterangan: ziarah kubur
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220016/kunjungan/{id}:
    put:
      tags:
        - Kunjungan
      summary: PUT
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                kuburan_id: 2
                tanggal_kunjungan: '2024-05-25'
                nama_pengunjung: Zamy Skibidi
                hubungan: friends
                keterangan: ziarah kubur
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Kunjungan
      summary: DELETE
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}